title: 'Jack, the skipper from Kansas'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/595dc33734f231ca9e0cfb6acc0e5c17f39a0cfa.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/595dc33734f231ca9e0cfb6acc0e5c17f39a0cfa.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/c64b418c5a7c5298635c94d7fc184b69/noop.jpg?input=https%3A%2F%2Fimg.youtube.com%2Fvi%2F-V75o-oKzAA%2Fmaxresdefault.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose:
  - type: external
    url: 'https://www.instagram.com/jblake_913/'
    label: 'DM on Instagram for Business Inquiries '
  - type: external
    url: 'https://www.heliofoodcompany.com/products/five-day-supply'
    label: TRY THIS
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Be the change you wish to see
color:
  saturation: 0.7616874
  brandStrength: 0.8888889
  rhythmicContrast: 0.9888954
  brandColors:
    - '#0A5F7A'
    - '#242827'
    - '#FDDDCB'
    - '#787FA1'
    - '#BFBBC9'
  lightness: 0.7258065
navigation:
  - name: 'Client: Helio, A Food Company'
    url: 'https://www.heliofoodcompany.com/pages/the-helio-story'
    type: external
  - name: About Me
    id: 85278aed-0129-494d-9fb4-14a46083a5ae
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
author:
  name: Jack
  email: jack3blake@gmail.com
favicon: null
opengraph:
  image: null
  type: null
  appId: '247996035605941'
name: Captain Jack
typography_spectrum: 0.7275985
layout_spectrum: 0.9659498
