title: Captain Jack's Blog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FyoAO0SrC2fM%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DyoAO0SrC2fM&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FyoAO0SrC2fM%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Jack Blake
          url: 'https://www.youtube.com/channel/UCgsPGTkZJoT6QFEn2vtUM_w'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - duration
        - legoland
        - vaynerchucks
        - waterslides
        - fanvee
        - playtime
        - drock
        - top5central
        - pool
        - '591'
      description: >-
        FanVee is a mashup from Gary Vaynerchucks videos. This week I took his
        intro (hope it's alright) and infused it with the networking and some
        highlights from Benton & Ryan's #Hustle with Helio Food Company. Love
        being their DRock.
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=yoAO0SrC2fM&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=yoAO0SrC2fM&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=yoAO0SrC2fM&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=yoAO0SrC2fM&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=yoAO0SrC2fM&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=yoAO0SrC2fM'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=yoAO0SrC2fM
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=yoAO0SrC2fM
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=yoAO0SrC2fM'
      title: '#FanVee - Kansas City''s Own #VaynerTalent'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose:
  - type: external
    url: 'https://www.instagram.com/jblake_913/'
    label: 'DM on Instagram for Business Inquiries '
  - type: external
    url: 'https://www.heliofoodcompany.com/products/five-day-supply'
    label: TRY THIS
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'Perspectives From My Daily Endeavors '
color:
  saturation: 0.7616874
  brandStrength: 0.8888889
  rhythmicContrast: 0.9888954
  brandColors:
    - '#0A5F7A'
    - '#242827'
    - '#FDDDCB'
    - '#787FA1'
    - '#BFBBC9'
  lightness: 0.7258065
navigation:
  - name: 'Client: Helio, A Food Company'
    url: 'https://www.heliofoodcompany.com/pages/the-helio-story'
    type: external
  - name: About Me
    id: 85278aed-0129-494d-9fb4-14a46083a5ae
    type: content
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
author:
  name: Jack
  email: jack3blake@gmail.com
favicon: null
opengraph:
  image: null
  type: null
  appId: '247996035605941'
name: Captain Jack
typography_spectrum: 0.7275985
layout_spectrum: 0.9659498
