layout_spectrum: 0.17927574130577395
typography_spectrum: 0.32233285447656373
color:
  brandColors:
    - '#0A5F7A'
    - '#242827'
    - '#FDDDCB'
    - '#787FA1'
    - '#BFBBC9'
  brandStrength: 0.14450310997415963
  lightness: 0.9131563500126842
  saturation: 0.7616873973066743
  rhythmicContrast: 0.9888954212600457
github: true
opengraph:
  image: null
  type: null
  appId: '247996035605941'
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jack
  email: jack3blake@gmail.com
name: Captain Jack's Blog
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Client: Helio, A Food Company'
    url: 'https://www.heliofoodcompany.com/pages/the-helio-story'
    type: external
  - name: About Me
    id: 85278aed-0129-494d-9fb4-14a46083a5ae
    type: content
favicon: null
title: Captain Jack's Blog
content: []
description: 'Perspectives From My Daily Endeavors '
purpose:
  - type: external
    url: 'https://www.instagram.com/jblake_913/'
    label: 'DM on Instagram for Business Inquiries '
  - type: external
    url: 'https://www.heliofoodcompany.com/products/five-day-supply'
    label: TRY THIS
